# Generated by Django 4.2.16 on 2024-10-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartitems_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
