# Generated by Django 4.2.17 on 2024-12-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_otprecord_tempuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
