# Generated by Django 4.2.17 on 2025-01-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_delivery_agent",
            field=models.BooleanField(default=False),
        ),
    ]
