# Generated by Django 5.1.3 on 2025-01-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_is_delivery_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
