# Generated by Django 5.1.3 on 2025-02-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_is_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_supplier',
        ),
    ]
