# Generated by Django 4.2.17 on 2025-02-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_transactions_transaction_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempuser",
            name="name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
