# Generated by Django 5.1.3 on 2025-02-18 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_userwallet_user_alter_userwallet_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='wallet_amount',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
