# Generated by Django 4.2.16 on 2024-11-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
