# Generated by Django 5.1.3 on 2025-01-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitems_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in-transit', 'In Transit'), ('out-for-delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=55),
        ),
    ]
