# Generated by Django 5.1.3 on 2025-02-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
