# Generated by Django 4.2.17 on 2025-02-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_foodpairing_wineevent_winerecommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
