# Generated by Django 5.1.3 on 2025-02-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
