# Generated by Django 5.1.3 on 2025-02-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_min_stock_threshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
