# Generated by Django 5.1.3 on 2025-02-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acidity',
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alcohol_content',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taste',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
